// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Approved Solar Retailer', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Approved Solar Retailer', async function() {
    await driver.get("https://verticdev-cleanenergycouncil.cs58.force.com/ComplaintForm")
    await driver.findElement(By.id("natureComplaint")).click()
    {
      const dropdown = await driver.findElement(By.id("natureComplaint"))
      await dropdown.findElement(By.css("*[value='Make a complaint against an Approved Solar retailer']")).click()
    }
    await driver.findElement(By.id("firstName")).click()
    await driver.findElement(By.id("firstName")).sendKeys("Selenium")
    await driver.findElement(By.id("lastName")).sendKeys("Test")
    await driver.findElement(By.id("email")).sendKeys("ddd@gmail.com")
    await driver.findElement(By.xpath("//group-input/input")).sendKeys("3778 893 737")
    await driver.findElement(By.id("streetAddress")).sendKeys("ggd")
    await driver.findElement(By.id("mailingCity")).sendKeys("mel")
    await driver.findElement(By.id("postCode")).sendKeys("123355677899")
    {
      const dropdown = await driver.findElement(By.id("mailingState"))
      await dropdown.findElement(By.css("*[value='NT']")).click()
    }
    await driver.findElement(By.id("companyName")).click()
    await driver.findElement(By.id("companyName")).sendKeys("Selenium")
    await driver.findElement(By.id("companyContactName")).click()
    await driver.findElement(By.id("city")).click()
    await driver.findElement(By.id("city")).sendKeys("mel")
    {
      const dropdown = await driver.findElement(By.id("state"))
      await dropdown.findElement(By.css("*[value='NT']")).click()
    }
    await driver.findElement(By.css(".input-group > #dateOfInstallation")).click()
    await driver.findElement(By.css("tr:nth-child(1) > .day:nth-child(2)")).click()
    await driver.findElement(By.id("If so, what was the retailer\'s response?")).click()
    await driver.findElement(By.id("If so, what was the retailer\'s response?")).sendKeys("eee")
    await driver.findElement(By.id("Please detail the breach of the code")).click()
    await driver.findElement(By.id("Please detail the breach of the code")).sendKeys("rrr")
    await driver.findElement(By.id("contactedTheRetailerInvolved")).click()
    {
      const dropdown = await driver.findElement(By.id("contactedTheRetailerInvolved"))
      await dropdown.findElement(By.css("*[value='No']")).click()
    }
    await driver.findElement(By.css(".btn")).click()
    await driver.wait(until.elementLocated(By.xpath("//h2[contains(.,\'Your complaint has been submitted successfully.\')]")), 15000)
  })
})
