// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Report a product fault', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Report a product fault', async function() {
    await driver.get("https://verticdev-cleanenergycouncil.cs58.force.com/ComplaintForm")
    await driver.findElement(By.id("natureComplaint")).click()
    {
      const dropdown = await driver.findElement(By.id("natureComplaint"))
      await dropdown.findElement(By.css("*[value='Report a product fault']")).click()
    }
    await driver.findElement(By.css(".col-sm-12:nth-child(1) .checkbox-text")).click()
    await driver.findElement(By.id("firstName")).sendKeys("Selenium")
    await driver.findElement(By.id("lastName")).sendKeys("Test")
    await driver.findElement(By.id("email")).sendKeys("ddd@gmail.com")
    await driver.findElement(By.css(".ng-scope > .form-control")).sendKeys("3778 893 737")
    await driver.findElement(By.id("streetAddress")).sendKeys("ggd")
    await driver.findElement(By.id("mailingCity")).sendKeys("mel")
    await driver.findElement(By.id("postCode")).sendKeys("123355677899")
    {
      const dropdown = await driver.findElement(By.id("mailingState"))
      await dropdown.findElement(By.css("*[value='NT']")).click()
    }
    await driver.findElement(By.css(".input-group > #dateOfInstallation")).click()
    await driver.findElement(By.css("tr:nth-child(1) > .day:nth-child(2)")).click()
    await driver.findElement(By.css(".btn")).click()
    await driver.wait(until.elementLocated(By.xpath("//h2[contains(.,\'Thank you for reporting this product fault. The fault will be investigated and appropriate action will be taken if deemed necessary.\')]")), 15000)
  })
})
