// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Inverter Application', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Inverter Application', async function() {
    await driver.get("https://verticdev-cleanenergycouncil.cs58.force.com/apex/InverterApplication?skip-files")
    vars["href"] = await driver.executeScript("return window.location.href")
    await driver.findElement(By.id("gridInteractivePort__1Yes")).click()
    await driver.findElement(By.id("otherEnergySource__4Yes")).click()
    await driver.findElement(By.id("standAlongPort__5_1Yes")).click()
    await driver.findElement(By.id("upsFunctionNote2__10_3Yes")).click()
    await driver.findElement(By.xpath("//group-input/input")).click()
    await driver.findElement(By.xpath("//group-input/input")).sendKeys("Selenium")
    await driver.findElement(By.id("preferredBusinessName")).sendKeys("Selenium")
    await driver.findElement(By.id("firstName")).sendKeys("Selenium")
    await driver.findElement(By.id("lastName")).sendKeys("Test")
    await driver.findElement(By.id("email")).sendKeys("ddd@gmail.com")
    await driver.findElement(By.css(".c-google-address-autocomplete > #address")).sendKeys("ggd")
    await driver.findElement(By.id("preferredBusinessName")).click()
    await driver.findElement(By.id("preferredBusinessName")).sendKeys("Selenium")
    await driver.findElement(By.id("mailingStreet")).click()
    await driver.findElement(By.id("mailingStreet")).sendKeys("ggd")
    await driver.findElement(By.id("mailingCity")).sendKeys("mel")
    await driver.findElement(By.id("mailingState")).sendKeys("NT")
    await driver.findElement(By.id("mailingPostalCode")).sendKeys("123355677899")
    await driver.findElement(By.xpath("//div[12]/div/form-group/div/div/div/group-input/input")).sendKeys("37 7889 3737")
    await driver.findElement(By.id("TradingName")).sendKeys("Selenium")
    {
      const dropdown = await driver.findElement(By.id("country"))
      await dropdown.findElement(By.css("*[value='Australia']")).click()
    }
    await driver.findElement(By.id("ManufacturerDistributer")).sendKeys("2345677")
    await driver.findElement(By.id("CertificateNumbers")).sendKeys("1488694737382938757575")
    await driver.findElement(By.id("CertifyingBody")).sendKeys("ggggg")
    await driver.findElement(By.css(".input-group > #expiryDate")).sendKeys("31/12/2030")
    await driver.findElement(By.css(".row:nth-child(30) .checkbox-text")).click()
    await driver.findElement(By.css(".row:nth-child(31) .checkbox-text")).click()
    await driver.findElement(By.css(".row:nth-child(32) .checkbox-text")).click()
    await driver.findElement(By.css(".ng-empty > .c-vertic_FormGroup .checkbox-text")).click()
    await driver.findElement(By.css("p > .btn")).click()
    await driver.sleep(12000)
    vars["new_href"] = await driver.executeScript("return window.location.href")
    if (!!await driver.executeScript("return (arguments[0] == arguments[1])", vars["href"],vars["new_href"])) {
      await driver.close()
    }
  })
})
