// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('PVModuleApplication', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('firefox').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('PVModuleApplication', async function() {
    await driver.get("https://verticdev-cleanenergycouncil.cs58.force.com/apex/PVModuleApplication?skip-files")
    vars["href"] = await driver.executeScript("return window.location.href")
    await driver.findElement(By.name("companyName")).click()
    await driver.findElement(By.name("companyName")).sendKeys("Selenium")
    await driver.findElement(By.id("PreferredBusinessName")).sendKeys("Selenium")
    await driver.findElement(By.id("firstName")).sendKeys("Selenium")
    await driver.findElement(By.id("lastName")).sendKeys("Test")
    await driver.findElement(By.id("email")).sendKeys("ddd@gmail.com")
    await driver.findElement(By.css(".c-google-address-autocomplete > #address")).sendKeys("ggd")
    await driver.findElement(By.id("townSuburb")).sendKeys("mel")
    await driver.findElement(By.id("state")).sendKeys("NT")
    await driver.findElement(By.id("postcode")).sendKeys("123355677899")
    await driver.findElement(By.id("country")).click()
    {
      const dropdown = await driver.findElement(By.id("country"))
      await dropdown.findElement(By.css("*[value='Australia']")).click()
    }
    await driver.findElement(By.id("streetAddress")).click()
    await driver.findElement(By.id("streetAddress")).sendKeys("ggd")
    await driver.findElement(By.id("townSuburb")).sendKeys("mel")
    await driver.findElement(By.id("state")).sendKeys("NT")
    await driver.findElement(By.id("postcode")).sendKeys("123355677899")
    await driver.findElement(By.id("TradingName")).sendKeys("Selenium")
    await driver.findElement(By.id("ManufacturerEmail")).sendKeys("ddd@gmail.com")
    await driver.findElement(By.id("ManufacturerDistributer")).click()
    await driver.findElement(By.id("ManufacturerDistributer")).sendKeys("2345677")
    await driver.findElement(By.id("CertifyingBody")).click()
    await driver.findElement(By.id("CertifyingBody")).sendKeys("ggggg")
    await driver.findElement(By.id("CertificateNumbers")).click()
    await driver.findElement(By.id("CertificateNumbers")).sendKeys("1488694737382938757575")
    await driver.findElement(By.id("ImporterResponsibleSupplier1")).click()
    await driver.findElement(By.id("ImporterResponsibleSupplier1")).sendKeys("fff")
    await driver.findElement(By.id("ABNSupplier1")).click()
    await driver.findElement(By.id("ABNSupplier1")).sendKeys("aaa")
    await driver.findElement(By.id("EmailSupplier1")).click()
    await driver.findElement(By.id("EmailSupplier1")).sendKeys("ddd@gmail.com")
    await driver.findElement(By.css(".ng-scope > .form-control")).click()
    await driver.findElement(By.css(".ng-scope > .form-control")).sendKeys("8377 889 373")
    await driver.findElement(By.id("WebsiteSupplier1")).click()
    await driver.findElement(By.id("WebsiteSupplier1")).sendKeys("https://dkdkd.com")
    await driver.findElement(By.css(".checkboxes:nth-child(25) .checkbox-text")).click()
    await driver.findElement(By.css(".checkboxes:nth-child(26) .checkbox-text")).click()
    await driver.findElement(By.css(".checkboxes:nth-child(27) .checkbox-text")).click()
    await driver.findElement(By.css(".checkboxes:nth-child(28) .checkbox-text")).click()
    await driver.findElement(By.css(".checkboxes:nth-child(29) .checkbox-text")).click()
    await driver.findElement(By.css(".ng-empty > .c-vertic_FormGroup .checkbox-text")).click()
    await driver.findElement(By.css(".margin-top-40 > .btn")).click()
    await driver.sleep(12000)
    vars["new_href"] = await driver.executeScript("return window.location.href")
    if (!!await driver.executeScript("return (arguments[0] == arguments[1])", vars["href"],vars["new_href"])) {
      await driver.close()
    }
  })
})
